"""adds updated_by column

Revision ID: 160ad91c70b5
Revises: ddc4606f9a56
Create Date: 2025-07-21 13:28:01.157081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160ad91c70b5'
down_revision = 'ddc4606f9a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('users_deleted_by_fkey', type_='foreignkey')
        batch_op.drop_column('deleted_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('users_deleted_by_fkey', 'users', ['deleted_by'], ['id'])
        batch_op.alter_column('updated_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
